### ISSUE TITLE
Docker automatic HTTPS configuration - incorrect indentation of yaml

### ISSUE THREAD

**Issue by vanyabrucker** [passbolt/passbolt-docs#8]
On this documentation page: https://www.passbolt.com/docs/hosting/configure/https/ce/docker-auto/

The headers.yaml is not correctly indented and won't work. _middlewares_ should be two spaces to the right.

```
http:
middlewares:
  SslHeader:
    headers:
      FrameDeny: true
      AccessControlAllowMethods: 'GET,OPTIONS,PUT'
      AccessControlAllowOriginList:
        - origin-list-or-null
      AccessControlMaxAge: 100
      AddVaryHeader: true
      BrowserXssFilter: true
      ContentTypeNosniff: true
      ForceSTSHeader: true
      STSIncludeSubdomains: true
      STSPreload: true
      ContentSecurityPolicy: default-src 'self' 'unsafe-inline'
      CustomFrameOptionsValue: SAMEORIGIN
      ReferrerPolicy: same-origin
      PermissionsPolicy: vibrate 'self'
      STSSeconds: 315360000
```
